apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://audit-prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://audit-loki:3100
    editable: true

  - name: Audit DB
    uid: audit-db
    type: postgres
    access: proxy
    url: audit-db:5432
    user: audit_user
    secureJsonData:
      password: audit_password
    jsonData:
      database: audit_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
